// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/art-detail/:id": {
    params: {
      "id": string;
    };
  };
  "/current-event": {
    params: {};
  };
  "/my-gallery": {
    params: {};
  };
  "/participate": {
    params: {};
  };
  "/previous-events": {
    params: {};
  };
  "/event-gallery/:id": {
    params: {
      "id": string;
    };
  };
  "/upload": {
    params: {};
  };
  "/upload/:id": {
    params: {
      "id": string;
    };
  };
  "/vote-art": {
    params: {};
  };
  "/vote-art/:id": {
    params: {
      "id": string;
    };
  };
  "/vote-theme": {
    params: {};
  };
  "/vote-complete/:artId": {
    params: {
      "artId": string;
    };
  };
  "/edit-art/:id": {
    params: {
      "id": string;
    };
  };
  "/destroy-art/:artId": {
    params: {
      "artId": string;
    };
  };
  "/upload-success/:id": {
    params: {
      "id": string;
    };
  };
  "/kiosk/home": {
    params: {};
  };
  "/kiosk/about": {
    params: {};
  };
  "/kiosk/previous-event-gallery": {
    params: {};
  };
  "/kiosk/upload-info": {
    params: {};
  };
  "/kiosk/vote-art": {
    params: {};
  };
  "/kiosk/vote-complete/:id": {
    params: {
      "id": string;
    };
  };
  "/kiosk/vote-theme": {
    params: {};
  };
  "/kiosk/vote": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about" | "/art-detail/:id" | "/current-event" | "/my-gallery" | "/participate" | "/previous-events" | "/event-gallery/:id" | "/upload" | "/upload/:id" | "/vote-art" | "/vote-art/:id" | "/vote-theme" | "/vote-complete/:artId" | "/edit-art/:id" | "/destroy-art/:artId" | "/upload-success/:id" | "/kiosk/home" | "/kiosk/about" | "/kiosk/previous-event-gallery" | "/kiosk/upload-info" | "/kiosk/vote-art" | "/kiosk/vote-complete/:id" | "/kiosk/vote-theme" | "/kiosk/vote";
  };
  "layouts/BaseLayoutWebsite.jsx": {
    id: "layouts/BaseLayoutWebsite";
    page: "/" | "/about" | "/art-detail/:id" | "/current-event" | "/my-gallery" | "/participate" | "/previous-events" | "/event-gallery/:id" | "/upload" | "/upload/:id" | "/vote-art" | "/vote-art/:id" | "/vote-theme" | "/vote-complete/:artId" | "/edit-art/:id" | "/destroy-art/:artId" | "/upload-success/:id";
  };
  "routes/website/home.jsx": {
    id: "routes/website/home";
    page: "/";
  };
  "routes/website/about.jsx": {
    id: "routes/website/about";
    page: "/about";
  };
  "routes/website/art-detail.jsx": {
    id: "routes/website/art-detail";
    page: "/art-detail/:id";
  };
  "routes/website/current-event.jsx": {
    id: "routes/website/current-event";
    page: "/current-event";
  };
  "routes/website/my-gallery.jsx": {
    id: "routes/website/my-gallery";
    page: "/my-gallery";
  };
  "routes/website/participate.jsx": {
    id: "routes/website/participate";
    page: "/participate";
  };
  "routes/website/previous-events.jsx": {
    id: "routes/website/previous-events";
    page: "/previous-events";
  };
  "routes/website/event-gallery.jsx": {
    id: "routes/website/event-gallery";
    page: "/event-gallery/:id";
  };
  "routes/website/upload-list.jsx": {
    id: "routes/website/upload-list";
    page: "/upload";
  };
  "routes/website/upload.jsx": {
    id: "routes/website/upload";
    page: "/upload/:id";
  };
  "routes/website/vote-art.jsx": {
    id: "routes/website/vote-art";
    page: "/vote-art";
  };
  "routes/website/art-category.jsx": {
    id: "routes/website/art-category";
    page: "/vote-art/:id";
  };
  "routes/website/vote-theme.jsx": {
    id: "routes/website/vote-theme";
    page: "/vote-theme";
  };
  "routes/website/vote-complete.jsx": {
    id: "routes/website/vote-complete";
    page: "/vote-complete/:artId";
  };
  "routes/website/edit-art.jsx": {
    id: "routes/website/edit-art";
    page: "/edit-art/:id";
  };
  "routes/website/destroy-art.jsx": {
    id: "routes/website/destroy-art";
    page: "/destroy-art/:artId";
  };
  "routes/website/upload-success.jsx": {
    id: "routes/website/upload-success";
    page: "/upload-success/:id";
  };
  "layouts/BaseLayoutKiosk.jsx": {
    id: "layouts/BaseLayoutKiosk";
    page: "/kiosk/home" | "/kiosk/about" | "/kiosk/previous-event-gallery" | "/kiosk/upload-info" | "/kiosk/vote-art" | "/kiosk/vote-complete/:id" | "/kiosk/vote-theme" | "/kiosk/vote";
  };
  "routes/kiosk/home.jsx": {
    id: "routes/kiosk/home";
    page: "/kiosk/home";
  };
  "routes/kiosk/about.jsx": {
    id: "routes/kiosk/about";
    page: "/kiosk/about";
  };
  "routes/kiosk/previous-event-gallery.jsx": {
    id: "routes/kiosk/previous-event-gallery";
    page: "/kiosk/previous-event-gallery";
  };
  "routes/kiosk/upload-info.jsx": {
    id: "routes/kiosk/upload-info";
    page: "/kiosk/upload-info";
  };
  "routes/kiosk/vote-art.jsx": {
    id: "routes/kiosk/vote-art";
    page: "/kiosk/vote-art";
  };
  "routes/kiosk/vote-complete.jsx": {
    id: "routes/kiosk/vote-complete";
    page: "/kiosk/vote-complete/:id";
  };
  "routes/kiosk/vote-theme.jsx": {
    id: "routes/kiosk/vote-theme";
    page: "/kiosk/vote-theme";
  };
  "routes/kiosk/vote.jsx": {
    id: "routes/kiosk/vote";
    page: "/kiosk/vote";
  };
};